name: gql_client
description: Tiny Client for Graphql
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.4
