targets:
  gql_gapher:gql_gapher:
    builders:
      gql_gapher|gql_gapher_builder:
        enabled: True

builders:
  gql_gapher_builder:
    import: "package:gql_gapher/gql_gapher.dart"
    builder_factories: ["gqlBuilder"]
    build_extensions: { ".graphql": [".g.dart"], ".gql": [".g.dart"] }
    auto_apply: root_package
    build_to: source
